blank_issues_enabled: false
contact_links:
  - name: Windows Update Viewer Discussions ğŸ—£ï¸
    url: https://github.com/Timthreetwelve/WUView/discussions
    about: If you have a question or some feedback, start a discussion. 
